# SPDX-FileCopyrightText: Copyright (c) 2014-2026 Yegor Bugayenko
# SPDX-License-Identifier: MIT
---
AllCops:
  Exclude:
    - 'bin/**/*'
  TargetRubyVersion: 2.0
  NewCops: enable

Metrics/MethodLength:
  Max: 50

Elegant/NoClassInModule:
  Exclude:
    - 'lib/**/*'
    - '**/test_*.rb'
    - '**/*Test.rb'

plugins:
  - rubocop-rake
  - rubocop-minitest
  - rubocop-performance
  - rubocop-elegant
